@startuml

skinparam defaultFontName Helvetica
skinparam defaultFontSize 11
skinparam ParticipantPadding 20
skinparam maxMessageSize 200

title Bucle de evaluación de los candidatos del flujo normal de la BO

actor       Usuario     as U
participant "Hilo GUI"         as GUI
participant "Hilo RT"          as RT
participant "Hilo NRT_BO"      as NRT

activate NRT

loop Para cada candidato (LHS + iteraciones BO)
  par
    NRT -> NRT : Decodifica parámetros del candidato
    loop last_synapse_idx_read_RT.load(relaxed)\n!= curr_synapse_idx
      NRT -> NRT : sleep_for(ACTIVE_WAIT_MS)
    end
  else
    RT ->> NRT : last_synapse_idx_read_RT.store(curr_synapse_idx, relaxed)
  end
  NRT -> NRT : new_synapse_idx = 1 - curr_synapse_idx
  NRT -> NRT : Escribe parámetros del candidato en params_XX[new_synapse_idx]
  NRT ->> RT : synapse_idx.store(new_synapse_idx, **release**)

  par
    RT -> RT : curr_synapse_idx = synapse_idx.load(**acquire**)
    activate RT
    RT ->> NRT : last_synapse_idx_read_RT.store(curr_synapse_idx, relaxed)
    loop Bucle de RT
      RT -> RT : Usa params_XX[curr_synapse_idx] para calcular sinapsis
    end
  else
    NRT -> NRT : curr_synapse_idx = new_synapse_idx
    NRT -> NRT : sleep_for(stabilization_time)
    NRT -> NRT : storing_idx = 0
  end

  NRT ->> RT : RT_storing.store(true, **release**)
  par
    loop Bucle de RT, mientras RT_storing.load(relaxed)\n== true y storing_idx < num_elements
      RT -> RT : Usa params_XX[curr_synapse_idx] para calcular sinapsis
      RT -> RT : Guarda datos en buffers (i_fast_sig_XX, i_slow_sig_XX, v_pre_sig_XX)\nstoring_idx++
    end
    RT ->> NRT : RT_storing.store(false, **release**)
    deactivate RT
  else
    loop RT_storing.load(**acquire**) == true
      NRT -> NRT : sleep_for(ACTIVE_WAIT_MS)
    end
  end

  NRT -> NRT : Evalúa candidato mediante buffers

  NRT ->> GUI : invokeMethod("set_evaluations_completed", evaluations_completed + 1)
  activate GUI
  GUI -> GUI : evaluations_completed++
  GUI ->> U : Muestra aumento en 1 de evaluaciones completadas
  deactivate GUI

end

@enduml
