HR1:
  e: 3.281
  mu: 0.0029
  S: 4
  a: 1
  b: 3
  c: 1
  d: 5
  xr: -1.6
  vh: 1
HR2:
  e: 3.281
  mu: 0.0039
  S: 4
  a: 1
  b: 3
  c: 1
  d: 5
  xr: -1.6
  vh: 1
Chemical-HR1-HR2:
  gfast: 5.0e-08
  Esyn: -0.05
  sfast: 50000.0
  Vfast: -0.042
  Vslow: -0.042
  gslow: 5.0e-08
  k1: 500.0
  k2: 100.0
  sslow: 250.0
Chemical-HR2-HR1:
  gfast: 0.015
  Esyn: -1.5
  sfast: 0.2
  Vfast: 0
  Vslow: 0
  gslow: 0.025
  k1: 1
  k2: 0.03
  sslow: 1
